### ISSUE TITLE
Positive passage ids duplicated in MS MARCO hard negatives?

### ISSUE THREAD

**Issue by surajnair04** [UKPLab/sentence-transformers#1346]
Hi Nils,

Thanks for releasing the MS MARCO hard negative dataset.
Upon viewing one of the training examples [here](https://huggingface.co/datasets/sentence-transformers/msmarco-hard-negatives), I see that the positive pid is duplicated in some of the mined negatives.
Attaching the snippet below:
```yaml
{
  "qid": 571018,
  "pos": [7349777],
  "neg": {
    "bm25": [...],
    "msmarco-distilbert-base-tas-b": [...],
    "msmarco-distilbert-base-v3": [...],
    "msmarco-MiniLM-L-6-v3": [...],
    "distilbert-margin_mse-cls-dot-v2": [7349777,],
    "distilbert-margin_mse-cls-dot-v1": [7349777,"..."],
    "distilbert-margin_mse-mean-dot-v1": [7349777,...],
    "mpnet-margin_mse-mean-v1": [..., 7349777, ...],
    "distilbert-margin_mse-mnrl-mean-v1": [7349777, ...],
    "distilbert-margin_mse-sym_mnrl-mean-v1": [7349777, ...],
    "distilbert-margin_mse-sym_mnrl-mean-v2": [7349777, ...],
    "co-condenser-margin_mse-sym_mnrl-mean-v1": [7349777, ...]
  }
}
```
This seems like a bug, right?
