### ISSUE TITLE
Model not working on Apple M1 Silicon

### ISSUE THREAD

**Issue by nishanthcgit** [UKPLab/sentence-transformers#1736]
Here is my code:

```
from sentence_transformers import SentenceTransformer, util
os.environ['PYTORCH_ENABLE_MPS_FALLBACK'] = '1'

# model = SentenceTransformer('all-MiniLM-L6-v2', device = device)
device = 'mps'
model = SentenceTransformer('multi-qa-mpnet-base-dot-v1', device = device)
refs = ['hello', 'how are you', 'abc']
sents = ['i am good thanks', 'def','hello how are you doing']

ref_embeddings = model.encode(refs, convert_to_tensor = True)
sent_embeddings = model.encode(sents, convert_to_tensor = True)

scores = util.cos_sim( sent_embeddings, ref_embeddings).detach()
```
Error message:
```
 NotImplementedError: The operator 'aten::cumsum.out' is not current implemented for the MPS device. If you want this op to be added in priority during the prototype phase of this feature, please comment on https://github.com/pytorch/pytorch/issues/77764. As a temporary fix, you can set the environment variable PYTORCH_ENABLE_MPS_FALLBACK=1 to use the CPU as a fallback for this op. WARNING: this will be slower than running natively on MPS.
```
I get that this is something not implemented in PyTorch itself but is there any workaround apart from using just CPU? Even setting the environment variable 'PYTORCH_ENABLE_MPS_FALLBACK' doesn't seem to make a difference. 
Woud also appreciate any other tips on getting sentence transformers to work with M1 silicon..

**Comment by jannikmi** [comment]
Have you tried using the nighltly build of pytorch with Apple Silicon support?

https://pytorch.org/get-started/locally/

**Comment by 2010b9** [comment]
I had the same problem, but setting the environment variable before importing torch solved the problem.

**Comment by wirtsi** [comment]
I was able to make it run by passing "mps" as a device to SentenceTransformer. Unfortunately it then starts leaking memory like crazy

**Comment by Vishwaak** [comment]
This model still has the same issue, setting env variable before the importing sentence transformer helped me.
`os.environ['PYTORCH_ENABLE_MPS_FALLBACK'] = '1'`

**Comment by adolfogc** [comment]
Hi, I'm currently experiencing an issue when using the MPS device for encoding --everything works fine when using the CPU device for encoding.

I was following the "Retrieve & Re-Rank Demo over Simple Wikipedia" example notebook, but the kernel hangs when running the following:

```python

if not torch.backends.mps.is_available():
    print("Warning: No GPU found. Please add GPU to your notebook")

DEVICE = torch.device("mps")

bi_encoder = SentenceTransformer('multi-qa-MiniLM-L6-cos-v1')

bi_encoder.max_seq_length = 256     #Truncate long passages to 256 tokens
top_k = 32                          #Number of passages we want to retrieve with the bi-encoder

bi_encoder.to(DEVICE) # <-- NOTE: does not work, process hangs

# bi_encoder.cpu() # <-- NOTE: works fine

# NOTE: progress bar reports having finished, but cell continues in the busy kernel state
corpus_embeddings = bi_encoder.encode(passages, convert_to_tensor=True, show_progress_bar=True) 
```

I am running the above in the following Conda environment:

```yaml
name: torch_env
channels:
  - pytorch-nightly
  - conda-forge
dependencies:
  - python=3.10
  - pytorch
  - torchvision
  - torchaudio
  - jupyterlab
  - matplotlib
  - pandas
  - pandas-profiling
  - numpy
  - scikit-learn
  - scipy
  - ipywidgets
  - widgetsnbextension
  - tqdm
  - pip
  - pip:
    - rank-bm25
    - git+https://github.com/UKPLab/sentence-transformers.git
```
